@startuml
participant SessionRepositoryFilter
participant SessionRepositoryFilter.SessionRepositoryRequestWrapper
participant CookieHttpSessionIdResolver
participant RedisOperationsSessionRepository
participant DefaultCookieSerializer

autonumber
activate SessionRepositoryFilter
SessionRepositoryFilter -> SessionRepositoryFilter.SessionRepositoryRequestWrapper: 调用getSession(true)方法
activate SessionRepositoryFilter.SessionRepositoryRequestWrapper
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> SessionRepositoryFilter.SessionRepositoryRequestWrapper: 调用getRequestedSession()方法
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> CookieHttpSessionIdResolver: 调用resolveSessionIds(this)查找sessionId
activate CookieHttpSessionIdResolver
CookieHttpSessionIdResolver ->DefaultCookieSerializer:调用readCookieValues方法，从cookie中获取sessionid
activate DefaultCookieSerializer
DefaultCookieSerializer -->CookieHttpSessionIdResolver:返回获取到的sessionid
deactivate DefaultCookieSerializer
CookieHttpSessionIdResolver --> SessionRepositoryFilter.SessionRepositoryRequestWrapper: 返回获取到的sessionId
deactivate CookieHttpSessionIdResolver
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> RedisOperationsSessionRepository: 调用findById(sessionId)，\n根据获取到的sessionid获取Session
activate RedisOperationsSessionRepository
RedisOperationsSessionRepository --> SessionRepositoryFilter.SessionRepositoryRequestWrapper:返回HttpSession
deactivate RedisOperationsSessionRepository
SessionRepositoryFilter.SessionRepositoryRequestWrapper --> SessionRepositoryFilter:返回HttpSession
deactivate SessionRepositoryFilter.SessionRepositoryRequestWrapper
deactivate SessionRepositoryFilter
@enduml