@startuml
participant SessionRepositoryFilter
participant SessionRepositoryFilter.SessionRepositoryRequestWrapper
participant RedisOperationsSessionRepository
participant RedisOperationsSessionRepository.RedisSession
participant CookieHttpSessionIdResolver

autonumber
activate SessionRepositoryFilter
SessionRepositoryFilter -> SessionRepositoryFilter: 调用doFilterInternal方法(设置session的总入口)
SessionRepositoryFilter -> SessionRepositoryFilter.SessionRepositoryRequestWrapper: 调用commitSession方法
activate SessionRepositoryFilter.SessionRepositoryRequestWrapper
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> SessionRepositoryFilter.SessionRepositoryRequestWrapper:调用getSession方法
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> RedisOperationsSessionRepository: 调用createSession方法生成session
activate RedisOperationsSessionRepository
RedisOperationsSessionRepository -> RedisOperationsSessionRepository.RedisSession: 实例化一个RedisSession对象，\n该对象包括了session的所有信息,其中sessionid是\n通过MapSession的generateId方法生成的。
activate RedisOperationsSessionRepository.RedisSession
RedisOperationsSessionRepository.RedisSession -->RedisOperationsSessionRepository: 返回生成的RedisSession对象
deactivate RedisOperationsSessionRepository.RedisSession
RedisOperationsSessionRepository --> SessionRepositoryFilter.SessionRepositoryRequestWrapper:返回生成的RedisSession对象
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> RedisOperationsSessionRepository: 调用save(session)方法\n将session信息保存到redis中
deactivate RedisOperationsSessionRepository
SessionRepositoryFilter.SessionRepositoryRequestWrapper -> CookieHttpSessionIdResolver: 调用setSessionId方法\n将sessionId保存到cookie中。
activate CookieHttpSessionIdResolver
CookieHttpSessionIdResolver -> DefaultCookieSerializer: 调用writeCookieValue将\nsessionid写入cookie中。\n这个方法还会写入其他的cookie属性，例如Path等。
activate DefaultCookieSerializer
deactivate DefaultCookieSerializer
deactivate CookieHttpSessionIdResolver
deactivate SessionRepositoryFilter.SessionRepositoryRequestWrapper
deactivate SessionRepositoryFilter
@enduml